### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Osborn-Lin** [RoboCupJuniorTC/rcj-soccersim#137]
I followed the instructions on github to download everything needed to use webots robocup simulation. However, when I run webots, it shows black screen. The time is moving, but nothing is not the screen. I tried zooming in/out. It doesn't' work.

**Comment by dbscoach** [comment]
What Webots version and what operating system are you using? Have you made sure rendering is enabled (there is a menu option to.turn rendering off and on, F6 also does it if I remember correctly).

**Comment by Adman** [comment]
Hello @Osborn-Lin, have you managed to fix the black screen problem?

**Comment by dbscoach** [comment]
I'll close this one for the time being, if you still have problems just re-open it.
